AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to Bootstrap the Common Resources

Parameters:
  # Delete this parameter after testing
  EventEngineParameter:
    Type: String
    Default: false
    Description: 'Tells if this workshop is running as a part of AWS Event through AWS EventEngine or not'

Conditions:
  # Delete this condition after testing
  IsNotRunningInEventEngine: !Not [!Equals [!Ref EventEngineParameter, true]]

Resources:
  DynamoDBTables:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/tables.yaml
  UserInterface:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/userinterface.yaml
      Parameters:
        IsCloudFrontAndS3PreProvisioned: !Ref EventEngineParameter

Outputs:
  AdminSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the tenant administration application
    Value: !GetAtt UserInterface.Outputs.AdminBucket
    Condition: IsNotRunningInEventEngine
  AdminAppSite:
    Description: The name of the CloudFront url for Admin Management site
    Value: !GetAtt UserInterface.Outputs.AdminAppSite
    Condition: IsNotRunningInEventEngine
  LandingApplicationSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the landing application
    Value: !GetAtt UserInterface.Outputs.LandingAppBucket
    Condition: IsNotRunningInEventEngine
  LandingApplicationSite:
    Description: The name of the CloudFront url for Landing site
    Value: !GetAtt UserInterface.Outputs.LandingApplicationSite
    Condition: IsNotRunningInEventEngine
  ApplicationSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the tenant application
    Value: !GetAtt UserInterface.Outputs.AppBucket
    Condition: IsNotRunningInEventEngine
  ApplicationSite:
    Description: The name of the CloudFront url for Tenant Management site
    Value: !GetAtt UserInterface.Outputs.ApplicationSite
    Condition: IsNotRunningInEventEngine
  ServerlessSaaSSettingsTableName:
    Description: The Name of DynamoDB Table of ServerlessSaaSSettingsTableName
    Value: !GetAtt DynamoDBTables.Outputs.ServerlessSaaSSettingsTableName
  TenantStackMappingTableName:
    Description: The Name of DynamoDB Table of TenantStackMappingTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantStackMappingTableName
  TenantDetailsTableName:
    Description: The Name of DynamoDB Table of TenantDetailsTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantDetailsTableName
  TenantUserMappingTableName:
    Description: The Name of DynamoDB Table of TenantUserMappingTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantUserMappingTableName
