AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template to Bootstrap the Common Resources

Parameters:
  # Delete this parameter after testing
  EventEngineParameter:
    Type: String
    Default: false
    Description: 'Tells if this workshop is running as a part of AWS Event through AWS EventEngine or not'
  AdminEmailParameter:
    Type: String
    Default: 'test@test.com'
    Description: 'Enter system admin email address'
  SystemAdminRoleNameParameter:
    Type: String
    Default: 'SystemAdmin'
    Description: 'Enter the role name for system admin'
  AdminUserPoolCallbackURLParameter:
    Type: String
    Default: 'http://example.com'
    Description: 'Enter Admin Management userpool call back url'
  TenantUserPoolCallbackURLParameter:
    Type: String
    Default: 'http://example.com'
    Description: 'Enter Tenant Management userpool call back url'

Conditions:
  # Delete this condition after testing
  IsNotRunningInEventEngine: !Not [!Equals [!Ref EventEngineParameter, true]]

Resources:
  DynamoDBTables:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/tables.yaml

  UserInterface:
    Type: AWS::Serverless::Application
    Properties:
      Location: nested_templates/userinterface.yaml
      Parameters:
        IsCloudFrontAndS3PreProvisioned: !Ref EventEngineParameter

  Cognito:
    Type: AWS::Serverless::Application
    DependsOn: UserInterface
    Properties:
      Location: nested_templates/cognito.yaml
      Parameters:
        AdminEmailParameter: !Ref AdminEmailParameter
        SystemAdminRoleNameParameter: !Ref SystemAdminRoleNameParameter
        AdminUserPoolCallbackURLParameter:
          !If [
            IsNotRunningInEventEngine,
            !GetAtt UserInterface.Outputs.AdminAppSite,
            !Ref AdminUserPoolCallbackURLParameter,
          ]
        TenantUserPoolCallbackURLParameter:
          !If [
            IsNotRunningInEventEngine,
            !GetAtt UserInterface.Outputs.ApplicationSite,
            !Ref TenantUserPoolCallbackURLParameter,
          ]

Outputs:
  AdminSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the tenant administration application
    Value: !GetAtt UserInterface.Outputs.AdminBucket
    Condition: IsNotRunningInEventEngine
  AdminAppSite:
    Description: The name of the CloudFront url for Admin Management site
    Value: !GetAtt UserInterface.Outputs.AdminAppSite
    Condition: IsNotRunningInEventEngine
  LandingApplicationSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the landing application
    Value: !GetAtt UserInterface.Outputs.LandingAppBucket
    Condition: IsNotRunningInEventEngine
  LandingApplicationSite:
    Description: The name of the CloudFront url for Landing site
    Value: !GetAtt UserInterface.Outputs.LandingApplicationSite
    Condition: IsNotRunningInEventEngine
  ApplicationSiteBucket:
    Description: The S3 Bucket that will contain the static assets for the tenant application
    Value: !GetAtt UserInterface.Outputs.AppBucket
    Condition: IsNotRunningInEventEngine
  ApplicationSite:
    Description: The name of the CloudFront url for Tenant Management site
    Value: !GetAtt UserInterface.Outputs.ApplicationSite
    Condition: IsNotRunningInEventEngine
  ServerlessSaaSSettingsTableName:
    Description: The Name of DynamoDB Table of ServerlessSaaSSettingsTableName
    Value: !GetAtt DynamoDBTables.Outputs.ServerlessSaaSSettingsTableName
  TenantStackMappingTableName:
    Description: The Name of DynamoDB Table of TenantStackMappingTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantStackMappingTableName
  TenantDetailsTableName:
    Description: The Name of DynamoDB Table of TenantDetailsTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantDetailsTableName
  TenantUserMappingTableName:
    Description: The Name of DynamoDB Table of TenantUserMappingTableName
    Value: !GetAtt DynamoDBTables.Outputs.TenantUserMappingTableName
  CognitoOperationUsersUserPoolId:
    Description: The user pool id of Admin Management userpool
    Value: !GetAtt Cognito.Outputs.CognitoOperationUsersUserPoolId
    Export:
      Name: 'Serverless-SaaS-CognitoOperationUsersUserPoolId'
  CognitoOperationUsersUserPoolProviderURL:
    Description: The Admin Management userpool provider url
    Value: !GetAtt Cognito.Outputs.CognitoOperationUsersUserPoolProviderURL
  CognitoOperationUsersUserPoolClientId:
    Description: The Admin Management userpool client id
    Value: !GetAtt Cognito.Outputs.CognitoOperationUsersUserPoolClientId
    Export:
      Name: 'Serverless-SaaS-CognitoOperationUsersUserPoolClientId'
  CognitoTenantUserPoolId:
    Description: The user pool id for tenant user pool
    Value: !GetAtt Cognito.Outputs.CognitoUserPoolId
    Export:
      Name: 'Serverless-SaaS-CognitoTenantUserPoolId'
  CognitoTenantAppClientId:
    Description: The app client id for tenant user pool
    Value: !GetAtt Cognito.Outputs.CognitoUserPoolClientId
    Export:
      Name: 'Serverless-SaaS-CognitoTenantAppClientId'
